### ISSUE TITLE
[Feature Request] X-Forwarded-For Support

### ISSUE THREAD

**Issue by coladarci** [WTTJ/algoliax#64]
So far this library is working quite nicely and was super easy to setup. 

The only thing I am blocked on is being able to pass the end user's IP address to Algolia for location-aware features (https://www.algolia.com/doc/guides/search-analytics/concepts/query-aggregation/#forward-user-ip-addresses) 

Do you have any advice on how you'd approach a PR for this? I'd be more than happy to do the work!

To my eyes:

```
  defp request_headers do
    [
      {"Content-type", "application/json"},
      {"X-Algolia-API-Key", Config.api_key()},
      {"X-Algolia-Application-Id", Config.application_id()}
    ]
  end
```

Would need to accept the incoming `request.body`; the only hacky thing would be that we would need to accept a sort of magic param in the body that wouldn't be passed on to algolia. Otherwise, we'd need to add an attribute to `request/2` which feels a lot more complicated.

Thanks again for this project!

**Comment by StephaneRob** [comment]
Hey @coladarci,
I see two solutions:

- New attribute on `search/2` ex: `Index.search(query, %{}, [headers: [{"X-Forwarded-For", "<IP>"}])`. But you said a little bit more complicated 
- Relies on `Process` dictionary to execute the search request with a given context

```elixir
# yourapp
Algoliax.with_context([headers: [{"X-Forwarded-For", "<IP>"}], fn ->
  Index.search(query, %{})
end)
```

```elixir
  # lib/algoliax/client.ex
  defp request_headers do
    [
      {"Content-type", "application/json"},
      {"X-Algolia-API-Key", Config.api_key()},
      {"X-Algolia-Application-Id", Config.application_id()}
    ] ++ custom_headers()
  end

  defp custom_headers do
    Process.get(:algolia_headers, [])
  end
```
